#!/usr/bin/env bash
# Install System Inspector CLI: sysinspect · si
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BIN_DIR="${XDG_BIN_HOME:-$HOME/.local/bin}"

case "${1:-}" in
  --help|-h)
    echo "Usage: ./install.sh"
    echo "  Installs sysinspect + si into ~/.local/bin"
    exit 0
    ;;
  "")
    ;;
  *)
    echo "Unknown option: $1" >&2
    echo "Usage: ./install.sh" >&2
    exit 1
    ;;
esac

cd "$ROOT"
chmod +x "$ROOT/sysinspect" "$ROOT/si" 2>/dev/null || true

echo "→ Setting up Python virtualenv + dependencies…"
if [[ ! -d .venv ]]; then
  python3 -m venv .venv
fi
.venv/bin/pip install -q -U pip
.venv/bin/pip install -q -r requirements.txt

echo "→ Installing CLI to $BIN_DIR …"
mkdir -p "$BIN_DIR"

cat > "$BIN_DIR/sysinspect" <<EOF
#!/usr/bin/env bash
# Generated by System Inspector install.sh — do not hand-edit unless you know why.
exec "$ROOT/sysinspect" "\$@"
EOF

cat > "$BIN_DIR/si" <<EOF
#!/usr/bin/env bash
# Short alias for sysinspect
exec "$ROOT/sysinspect" "\$@"
EOF

chmod +x "$BIN_DIR/sysinspect" "$BIN_DIR/si"

echo
echo "Done."
echo
echo "Open a new terminal and try:"
echo "  si gpu"
echo "  si temps"
echo "  si help"
echo

case ":$PATH:" in
  *":$BIN_DIR:"*)
    echo "PATH already includes $BIN_DIR."
    ;;
  *)
    echo "Add ~/.local/bin to your PATH (one time):"
    echo
    echo "  echo 'export PATH=\"\$HOME/.local/bin:\$PATH\"' >> ~/.bashrc"
    echo "  source ~/.bashrc"
    echo
    echo "If you use fish/zsh, put the same export in that shell's config."
    ;;
esac
