#!/usr/bin/env bash
# Install System Inspector for everyday use:
#   - CLI on PATH:  sysinspect · si   (no server needed)
#   - optional GUI: desktop app menu entry
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BIN_DIR="${XDG_BIN_HOME:-$HOME/.local/bin}"
APP_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/applications"
ICON_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/icons/hicolor/256x256/apps"
WITH_DESKTOP=1

for arg in "$@"; do
  case "$arg" in
    --cli-only) WITH_DESKTOP=0 ;;
    --help|-h)
      echo "Usage: ./install.sh [--cli-only]"
      echo "  Installs sysinspect + si into ~/.local/bin"
      echo "  Default also adds a desktop app menu entry"
      exit 0
      ;;
  esac
done

cd "$ROOT"
chmod +x "$ROOT/sysinspect" "$ROOT/si" "$ROOT/SystemInspector" "$ROOT/run.sh" 2>/dev/null || true

echo "→ Setting up Python virtualenv + dependencies…"
if [[ ! -d .venv ]]; then
  python3 -m venv --system-site-packages .venv
fi
# Prefer system GI packages for desktop window (safe if missing)
if [[ -f .venv/pyvenv.cfg ]] && grep -q 'include-system-site-packages = false' .venv/pyvenv.cfg 2>/dev/null; then
  sed -i 's/include-system-site-packages = false/include-system-site-packages = true/' .venv/pyvenv.cfg || true
fi
.venv/bin/pip install -q -U pip
.venv/bin/pip install -q -r requirements.txt

echo "→ Installing CLI to $BIN_DIR …"
mkdir -p "$BIN_DIR"

# Thin wrappers so they work from any directory permanently
cat > "$BIN_DIR/sysinspect" <<EOF
#!/usr/bin/env bash
# Generated by System Inspector install.sh — do not hand-edit unless you know why.
exec "$ROOT/sysinspect" "\$@"
EOF

cat > "$BIN_DIR/si" <<EOF
#!/usr/bin/env bash
# Short alias for sysinspect
exec "$ROOT/sysinspect" "\$@"
EOF

chmod +x "$BIN_DIR/sysinspect" "$BIN_DIR/si"

if [[ "$WITH_DESKTOP" -eq 1 ]]; then
  echo "→ Installing desktop app menu entry…"
  mkdir -p "$APP_DIR" "$ICON_DIR"
  ICON_SRC="$ROOT/frontend/assets/logo.png"
  ICON_DST="$ICON_DIR/system-inspector.png"
  [[ -f "$ICON_SRC" ]] && cp "$ICON_SRC" "$ICON_DST"

  cat > "$APP_DIR/system-inspector.desktop" <<EOF
[Desktop Entry]
Type=Application
Name=System Inspector
Comment=Scan hardware specs and live system vitals
Exec=$ROOT/SystemInspector
Icon=system-inspector
Path=$ROOT
Terminal=false
Categories=System;Monitor;
StartupNotify=true
EOF
  chmod +x "$APP_DIR/system-inspector.desktop"
  if command -v update-desktop-database >/dev/null 2>&1; then
    update-desktop-database "$APP_DIR" 2>/dev/null || true
  fi
fi

echo
echo "Done."
echo
echo "CLI (no app/server required):"
echo "  sysinspect gpu"
echo "  si cpu temp"
echo "  sysinspect help"
echo
echo "GUI (opens a window; starts its own backend):"
echo "  SystemInspector   # or from app menu: System Inspector"
echo "  $ROOT/SystemInspector"
echo

# PATH check
case ":$PATH:" in
  *":$BIN_DIR:"*) 
    echo "PATH already includes $BIN_DIR — open a new terminal and try: sysinspect status"
    ;;
  *)
    echo "Add ~/.local/bin to your PATH (one time), then open a new terminal:"
    echo
    echo "  echo 'export PATH=\"\$HOME/.local/bin:\$PATH\"' >> ~/.bashrc"
    echo "  source ~/.bashrc"
    echo
    echo "If you use fish/zsh, put the same export in that shell's config."
    ;;
esac
